name: my_library
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.1 # request
  provider: ^6.0.0 # state management
  flutter_dotenv: ^5.0.2 # env
  flutter_secure_storage: ^9.1.1 # secure storage
  tuple: ^2.0.2
  flutter_bugfender: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
